source 'https://rubygems.org'

gem 'dry-inflector', '~> 0.2.0'
gem 'linguo', '~> 0.0.2'
gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'
gem 'sequel', '~> 5.42'
gem 'sqlite3', '~> 1.4', '>= 1.4.2'
gem 'telegram-bot-ruby', '~> 0.15.0'
